# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DirectoryWatcher < Formula
  desc ""
  homepage ""
  version "2.2.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seungyeop-lee/directory-watcher/releases/download/v2.2.7/directory-watcher_Darwin_x86_64.tar.gz"
      sha256 "85e1ce6301f7bd7c721ca75018abb61a8c0cc83a64c8b651ccdf9a8263e6fbbc"

      def install
        bin.install "directory-watcher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seungyeop-lee/directory-watcher/releases/download/v2.2.7/directory-watcher_Darwin_arm64.tar.gz"
      sha256 "22c2bdc8f42194a01ee8a66a4d6ba88c0f479cbf3c8a828ff4972e5af883b47f"

      def install
        bin.install "directory-watcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seungyeop-lee/directory-watcher/releases/download/v2.2.7/directory-watcher_Linux_arm64.tar.gz"
      sha256 "743f4baae77e7b7240336df4e98a041ecaf9a51042372314340e79b97b76d065"

      def install
        bin.install "directory-watcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/seungyeop-lee/directory-watcher/releases/download/v2.2.7/directory-watcher_Linux_x86_64.tar.gz"
      sha256 "6eace84929fe5343d31a7abae27eef1d08fc4fa9d6f52ba229c56594ee6e75df"

      def install
        bin.install "directory-watcher"
      end
    end
  end
end
