# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DirectoryWatcher < Formula
  desc ""
  homepage ""
  version "2.2.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/seungyeop-lee/directory-watcher/releases/download/v2.2.5/directory-watcher_Darwin_arm64.tar.gz"
      sha256 "c0d2934cf42a5279a855795772dc834d6f955b340fab2b06987a068815f5aaa9"

      def install
        bin.install "directory-watcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/seungyeop-lee/directory-watcher/releases/download/v2.2.5/directory-watcher_Darwin_x86_64.tar.gz"
      sha256 "aa9893893c18146d6dfc2ac3c36eeed44bd11ecc2a3d818926c5d193bb7bd035"

      def install
        bin.install "directory-watcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seungyeop-lee/directory-watcher/releases/download/v2.2.5/directory-watcher_Linux_arm64.tar.gz"
      sha256 "3595ef7f851819cd5c0dbaa72348470415e0bf9f230e45bad359f549038f780e"

      def install
        bin.install "directory-watcher"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/seungyeop-lee/directory-watcher/releases/download/v2.2.5/directory-watcher_Linux_x86_64.tar.gz"
      sha256 "c57c2fa05a89da446edc139b87f2736502e78a1e5a36717497a75a5a7907a4c1"

      def install
        bin.install "directory-watcher"
      end
    end
  end
end
